// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/graph_db.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class GraphDbBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GraphDbBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GraphDbBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initialize the storage (creates Storage instance)
  ffi.Pointer<Box> graphdb_init(ffi.Pointer<ffi.Char> boxName) {
    return _graphdb_init(boxName);
  }

  late final _graphdb_initPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<Box> Function(ffi.Pointer<ffi.Char>)>
      >('graphdb_init');
  late final _graphdb_init = _graphdb_initPtr
      .asFunction<ffi.Pointer<Box> Function(ffi.Pointer<ffi.Char>)>();

  /// Save nodes / edges from JSON string
  void graphdb_save_nodes(
    ffi.Pointer<Box> box,
    ffi.Pointer<ffi.Char> jsonData,
  ) {
    return _graphdb_save_nodes(box, jsonData);
  }

  late final _graphdb_save_nodesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)
        >
      >('graphdb_save_nodes');
  late final _graphdb_save_nodes = _graphdb_save_nodesPtr
      .asFunction<void Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)>();

  void graphdb_save_edges(
    ffi.Pointer<Box> box,
    ffi.Pointer<ffi.Char> jsonData,
  ) {
    return _graphdb_save_edges(box, jsonData);
  }

  late final _graphdb_save_edgesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)
        >
      >('graphdb_save_edges');
  late final _graphdb_save_edges = _graphdb_save_edgesPtr
      .asFunction<void Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)>();

  /// Load a single node by ID (returns malloc'ed string, free with graphdb_free_string)
  ffi.Pointer<ffi.Char> graphdb_load_node(
    ffi.Pointer<Box> box,
    ffi.Pointer<ffi.Char> nodeId,
  ) {
    return _graphdb_load_node(box, nodeId);
  }

  late final _graphdb_load_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<Box>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('graphdb_load_node');
  late final _graphdb_load_node = _graphdb_load_nodePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)
      >();

  /// Load edges for a node (returns malloc'ed JSON string)
  ffi.Pointer<ffi.Char> graphdb_load_edges(
    ffi.Pointer<Box> box,
    ffi.Pointer<ffi.Char> nodeId,
  ) {
    return _graphdb_load_edges(box, nodeId);
  }

  late final _graphdb_load_edgesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<Box>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('graphdb_load_edges');
  late final _graphdb_load_edges = _graphdb_load_edgesPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)
      >();

  /// Build indexes manually (optional, usually called internally)
  void graphdb_build_node_index(ffi.Pointer<Box> box) {
    return _graphdb_build_node_index(box);
  }

  late final _graphdb_build_node_indexPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Box>)>>(
        'graphdb_build_node_index',
      );
  late final _graphdb_build_node_index = _graphdb_build_node_indexPtr
      .asFunction<void Function(ffi.Pointer<Box>)>();

  void graphdb_build_edge_index(ffi.Pointer<Box> box) {
    return _graphdb_build_edge_index(box);
  }

  late final _graphdb_build_edge_indexPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Box>)>>(
        'graphdb_build_edge_index',
      );
  late final _graphdb_build_edge_index = _graphdb_build_edge_indexPtr
      .asFunction<void Function(ffi.Pointer<Box>)>();

  /// Estimate node chunk size from JSON (returns size in bytes)
  int graphdb_estimate_nodes_size(
    ffi.Pointer<Box> box,
    ffi.Pointer<ffi.Char> jsonData,
  ) {
    return _graphdb_estimate_nodes_size(box, jsonData);
  }

  late final _graphdb_estimate_nodes_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Size Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)
        >
      >('graphdb_estimate_nodes_size');
  late final _graphdb_estimate_nodes_size = _graphdb_estimate_nodes_sizePtr
      .asFunction<int Function(ffi.Pointer<Box>, ffi.Pointer<ffi.Char>)>();

  /// Free memory returned by load_node/load_edges
  void graphdb_free_string(ffi.Pointer<ffi.Char> str) {
    return _graphdb_free_string(str);
  }

  late final _graphdb_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'graphdb_free_string',
      );
  late final _graphdb_free_string = _graphdb_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}

final class GraphDB extends ffi.Opaque {}

typedef Box = GraphDB;
